// /Users/elle/code/vibe-duet/examples/evolve/output/goldberg_imbue_v3_ada2a552/gemini/step_18.js
// https://strudel.cc/#c2V0Y3BzKDEzMC82MC80KQpzYW1wbGVzKCdzaGFiZGEvc3BlZWNoOmNvbXB1dGUsZXhlY3V0ZSxzeXN0ZW0sZXJyb3Isd2FybmluZyxwcm90b2NvbCcpCnNhbXBsZXMoJ3NoYWJkYS9zcGVlY2gvamEtSlAvZjprZWlrb2t1JykKc2FtcGxlcygnc2hhYmRhL3NwZWVjaC9ydS1SVS9mOm9zaGlia2Esdm5pbWFuaXllJykKCiQ6IG5vdGUoImcyIH4gW2cyIGcyXSBbZzIgZDIgZzIgfl0iKQogIC5zbG93KDIpCiAgLnNvdW5kKCJzYXd0b290aCIpCiAgLnNoYXBlKDAuMykKICAubHBmKDQwMCkKICAubHBlbnYoNDAwMCkKICAuZ2FpbigwLjQpCgokOiBuKCI8ZzUgZDYgYmI1IGM2Pi8yIikKICAuZmFzdCg4KQogIC5zb3VuZCgicHVsc2UiKQogIC5yZWxlYXNlKDAuMikKICAubHBmKHNpbmUucmFuZ2UoNDAwLCAyNTAwKS5zbG93KDMpKQogIC5kZWxheSgwLjQpLmRmYigwLjQpCiAgLmdhaW4oMC4yKQoKJDogY2hvcmQoImcyOm1haiBiYjE6bWFqNyBlYjI6bWFqNyBjMjptNyIpCiAgLmV1Y2xpZCg1LCAxNikKICAuc2xvdygxNikKICAuc291bmQoInN1cGVyc2F3IikKICAuYXR0YWNrKDEpLnJlbGVhc2UoMikKICAubHBmKDkwMCkKICAucm9vbSgwLjkpLnNpemUoMC45KQogIC5nYWluKDAuMykKICAKJDogc3RhY2soCiAgICBzKCJiZCo0IiksCiAgICBzKCJ%2BIHNuIikKICApCiAgLmRyaXZlKDAuNikKICAuY3J1c2goNSkKICAuaHBmKDQwKQogIC5yb29tKDAuMikKICAuZ2FpbigwLjcpCgokOiBzKCJoaCIpCiAgLmV1Y2xpZCg3LDgpLmZhc3QoMikKICAuY29hcnNlKDEwKQogIC5ocGYoNzAwMCkKICAucGFuKHNhdy5yYW5nZSgwLjIsIDAuOCkuc2xvdygyKSkKICAuZGVsYXkoMC4zKS5kZmIoMC41KQogIC5nYWluKDAuMjUpCiAgCiQ6IHMoIjxzeXN0ZW0ga2Vpa29rdSBlcnJvciBwcm90b2NvbCBvc2hpYmthIHdhcm5pbmcgdm5pbWFuaXllPiIpCiAgLnNsb3coOCkKICAuc29tZXRpbWVzQnkoMC40LCByZXYpCiAgLnN0cmlhdGUocmFuZC5yYW5nZSgyLCA2NCkpCiAgLnNwZWVkKCI8LTEgMSAwLjU%2BIikKICAuZGpmKHJhbmQpCiAgLmdhaW4oMC41KQ%3D%3D
setcps(130/60/4)
samples('shabda/speech:compute,execute,system,error,warning,protocol')
samples('shabda/speech/ja-JP/f:keikoku')
samples('shabda/speech/ru-RU/f:oshibka,vnimaniye')

$: note("g2 ~ [g2 g2] [g2 d2 g2 ~]")
  .slow(2)
  .sound("sawtooth")
  .shape(0.3)
  .lpf(400)
  .lpenv(4000)
  .gain(0.4)

$: n("<g5 d6 bb5 c6>/2")
  .fast(8)
  .sound("pulse")
  .release(0.2)
  .lpf(sine.range(400, 2500).slow(3))
  .delay(0.4).dfb(0.4)
  .gain(0.2)

$: chord("g2:maj bb1:maj7 eb2:maj7 c2:m7")
  .euclid(5, 16)
  .slow(16)
  .sound("supersaw")
  .attack(1).release(2)
  .lpf(900)
  .room(0.9).size(0.9)
  .gain(0.3)
  
$: stack(
    s("bd*4"),
    s("~ sn")
  )
  .drive(0.6)
  .crush(5)
  .hpf(40)
  .room(0.2)
  .gain(0.7)

$: s("hh")
  .euclid(7,8).fast(2)
  .coarse(10)
  .hpf(7000)
  .pan(saw.range(0.2, 0.8).slow(2))
  .delay(0.3).dfb(0.5)
  .gain(0.25)
  
$: s("<system keikoku error protocol oshibka warning vnimaniye>")
  .slow(8)
  .sometimesBy(0.4, rev)
  .striate(rand.range(2, 64))
  .speed("<-1 1 0.5>")
  .djf(rand)
  .gain(0.5)
