// Bridge: Em → Cm (post-climax descent)
// The storm passing — E minor dissolving into C minor space
setcps(80/60/4)

// Em echoes fading — high notes ringing out
$: note("e5 b4 g4 e4")
  .slow(2)
  .sound("sine")
  .fm(3)
  .fmh(2)
  .decay(2)
  .sustain(0)
  .gain(0.15)
  .room(0.9)
  .size(0.9)
  .delay(0.6)
  .delaytime(0.375)
  .delayfeedback(0.6)

// Pivot: E → G → C (descending through shared tones)
$: note("<[e3,g3,b3] [g3,bb3,d4] [c3,eb3,g3]>")
  .slow(2)
  .sound("supersaw")
  .attack(2)
  .release(3)
  .lpf(800)
  .gain(0.12)
  .room(0.8)
  .detune(4)

// C minor bass entering from below, very quiet
$: note("~ ~ c2 ~")
  .sound("triangle")
  .gain(sine.range(0, 0.2).slow(2))
  .room(0.7)
  .lpf(400)
